wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.5
    start_time: 1667137707.859375
    t:
      1:
      - 2
      - 3
      - 51
      - 55
      2:
      - 2
      - 3
      - 51
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.10.5
      5: 0.13.2
      8:
      - 2
      - 5
      10:
      - 9
architecture:
  desc: null
  value: CNN
entity:
  desc: null
  value: CNN_test
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: <class 'keras.optimizers.optimizer_v2.adam.Adam'>
