wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1678301456.561031
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 3
      - 8
      - 13
      - 15
      - 16
      - 23
      4: 3.8.10
      5: 0.13.11
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 50
optimizer:
  desc: null
  value: adam
